version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:3456
      - REDIS_HOST=redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3456:3456"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - app-network
  
  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge