version: "3.8"

services:
  app-test:
    image: haaaaron/app-test
    container_name: app-test
    restart: unless-stopped
    ports:
      - "8080:8080" # Expose port 8080

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_INCLUDE_STOPPED=false # Optionally, only watch running containers
      - WATCHTOWER_CLEANUP=true # Remove old images after updating
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
