name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish to docker hub
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: "{{defaultContext}}:parti_3/exercise_3.1"
            push: true
            tags: haaaaron/app-test:latest
        
